// app/lib/drillData.ts
export const drillData = [
  {
    id: "school-earthquake",
    title: "School Earthquake Drill",
    description: "Practice Drop, Cover, and Hold procedures in a classroom setting with evacuation routes.",
    level: "Beginner",
    type: "Natural",
    duration: "10 min",
    participants: 1247,
    lastScore: "92%",
    completed: "2 days ago",
    scenarios: 3,
  },
  {
    id: "fire-evacuation",
    title: "Fire Evacuation Drill",
    description: "Navigate through smoke-filled corridors and practice proper evacuation procedures.",
    level: "Intermediate",
    type: "Natural",
    duration: "15 min",
    participants: 892,
    lastScore: "87%",
    completed: "1 week ago",
    scenarios: 4,
  },
  {
    id: "monsoon-flood",
    title: "Monsoon Flood Response",
    description: "Learn to respond to sudden flooding during school hours with proper safety measures.",
    level: "Advanced",
    type: "Natural",
    duration: "20 min",
    participants: 634,
    lastScore: "64%",
    completed: "3 days ago",
    scenarios: 5,
  },
  {
    id: "cyclone-shelter",
    title: "Cyclone Shelter Procedures",
    description: "Practice taking shelter during cyclone warnings and post-storm safety checks.",
    level: "Intermediate",
    type: "Natural",
    duration: "18 min",
    participants: 423,
    lastScore: "64%",
    completed: "Not attempted",
    scenarios: 4,
  },
  {
    id: "multi-hazard",
    title: "Multi-Hazard Emergency Response",
    description: "Advanced drill combining multiple disaster scenarios in sequence.",
    level: "Advanced",
    type: "Natural",
    duration: "25 min",
    participants: 156,
    lastScore: "64%",
    completed: "Not attempted",
    scenarios: 6,
  },
  {
    id: "road-collapse",
    title: "Road Collapse Response Drill",
    description: "Practice safe evacuation and emergency response steps when a road or ground surface suddenly collapses.",
    level: "Advanced",
    type: "Non-Natural",
    duration: "18 min",
    participants: 312,
    lastScore: "58%",
    completed: "Not attempted",
    scenarios: 5,
  },
];
